### ISSUE TITLE
guide to implement a Sql implementation for InstacneStore

### ISSUE THREAD

**Issue by yekanchi** [UiPath/CoreWF#115]
I'm interested into implementing a SqlInstanceStore and pull it here if this repo is right place for it.
just before going into code i wanted to know if there is any guide to help me.
What i want to do is to implement something like `PurchaseProcess` example of the WF which is implemented the instance store using XML serialization,  then i will save the XML to  a sql table.
Is this a proper implementation?

**Comment by lbargaoanu** [comment]
We are not interested at this time.

**Comment by lbargaoanu** [comment]
At this time we have no plans for an instance store.

**Comment by dmetzgar** [comment]
@yekanchi I'm sure there are other people interested in having a database instance store provider. Instance store implementations should be in their own repos since there's a well-known interface. I'd suggest following these instructions on [how to create a custom instance store](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-create-a-custom-instance-store).

Regarding XML serialization, I would suggest not going this route. The serializer for WF in the .NET Framework is the NetDataContractSerializer. NDCS writes type information so that when it's deserialized, the correct assemblies and types can be loaded. DataContractSerializer and XmlSerializer don't do this and NDCS was not ported to .NET Core/Standard. We use the JsonSerializer in our [JsonFileInstanceStore](https://github.com/UiPath-Open/corewf/blob/master/src/Test/JsonFileInstanceStore/JsonFileInstanceStore.cs) example because it has [an option](https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#TypeNameHandling) to write type info.

A couple other suggestions:

1. Use Entity Framework so you're not limited to just SQL Server. Also it can automatically create and migrate the database without explicitly running a SQL file, like was done with the .NET Framework.
2. Create a shim for CoreWF to call into the original [SqlWorkflowInstanceStore](https://docs.microsoft.com/en-us/dotnet/api/system.activities.durableinstancing.sqlworkflowinstancestore?view=netframework-4.8). Since the serialization will have to be different and people are likely to have already persisted instances in a database, the only way to migrate is to load the instances into memory with the original InstanceStore and then persist again with the new one.
