### ISSUE TITLE
Suggestion: C# expression parsing

### ISSUE THREAD

**Issue by deniszykov** [UiPath/CoreWF#46]
As I understand from readme file you need a c# expression parser to complete WWF this implementation. I have [one](https://github.com/deniszykov/csharp-eval-unity3d). I could 'clean' it from unrelated stuff and constricting licensing. If you specify an contract/interface to implement and location/folder where this code should be I would provide PR.

**Comment by ewinnington** [comment]
As described in #7  , I thought it was only the public facing API of TextExpressionCompiler.Compile() that needs to be replaced. Thing is, when I went in and tried to just "get it running using roslyn" I ended up in a nightmare of pulling in files and files of previous WWF code (because of VB code fragments). If you can get that function to work, I *think* it should be fine.

I would love to get some help by someone (like you) who knows more about compiling in runtime in C#.

**Comment by ewinnington** [comment]
I think #47, just merged, covers this functionality.
