### ISSUE TITLE
Use Portable.Xaml to implement the System.Activities.XamlIntegration

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#6]
This is referring to @cwensley's port of Portable.Xaml to the .NET Standard here: https://github.com/cwensley/Portable.Xaml

It seems the most promising choice in terms of implementing the features of XAML that WF needs.

**Comment by ewinnington** [comment]
I got the PortableXAML version compiling and running until I'm trying to create the Type and I get an exception: when the underlying type on a XamlType is known, but it is unknown for '{http://schemas.microsoft.com/netfx/2009/xaml/activities}Activity'' from the Portable.Xaml.dll!Portable.Xaml.Schema.XamlTypeInvoker.ThrowIfUnknown() Line 76 when it's trying to Create the instance of Activity (CreateInstance). 

Any idea?

Now I need to figure out how to register the types correctly... Pushing it to my branch as soon as it's cleaned up.

**Comment by cwensley** [comment]
@ewinnington you need to add the Portable.Xaml.Markup.XmlnsDefinitionAttrbute to the assemblies that define those types.

E.g.  `[assembly: XmlnsDefinition("http://schemas.microsoft.com/netfx/2009/xaml/activities", "Clr.Namespace.To.Activity.In.This.Assembly")]`

You can also define these in another assembly by setting the AssemblyName property of the XmlnsDefinitionAttribute.

Note that if you are instantiating your own `XamlSchemaContext` (which I recommend using a static instance if performance is a concern), that the assemblies you pass in the constructor must contain all the types you wish to use in xaml.

Hope this helps!

**Comment by ewinnington** [comment]
Wow! Thanks for the information. I'll do that and report the effect :)
You saved me a ton of time searching.

Update: Didn't seem to do the trick. I'll clean up the commit, push to my branch and have a tea. 
  
I'm not instantiating my XamlSchemaContext. My code is: 

```
string XamlText = @"
<Activity x:Class=""WFTemplate"" 
mva:VisualBasic.Settings=""Assembly references and imported namespaces for internal implementation""  
xmlns=""http://schemas.microsoft.com/netfx/2009/xaml/activities""  
xmlns:mc=""http://schemas.openxmlformats.org/markup-compatibility/2006""  x
mlns:mva=""clr-namespace:Microsoft.VisualBasic.Activities;assembly=System.Activities""  
xmlns:scg=""clr-namespace:System.Collections.Generic;assembly=mscorlib""  
xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"">   
<Sequence>     
<WriteLine Text=""HelloWorld"" />   
</Sequence> 
</Activity>";
           
var act = CoreWf.XamlIntegration.ActivityXamlServices.Load(GenerateStreamFromString(XamlText));
WorkflowInvoker.Invoke(act);
```

**Comment by ewinnington** [comment]
[It's up](https://github.com/ewinnington/corewf). It compiles. It doesn't work yet. ;)

Current state: 
Exception thrown: 'System.NotSupportedException' in Portable.Xaml.dll
An unhandled exception of type 'System.NotSupportedException' occurred in Portable.Xaml.dll
Current operation is valid only when the underlying type on a XamlType is known, but it is unknown for '{http://schemas.microsoft.com/netfx/2009/xaml/activities}Activity'

I need to register the types somewhere...

**Comment by cwensley** [comment]
Hm, maybe GitHub search isn't working quite right, but searching for XmlnsDefinition revealed no results on that repo.

**Comment by ewinnington** [comment]
I have one in https://github.com/ewinnington/corewf/blob/master/src/CoreWf/Activity.cs

**Comment by cwensley** [comment]
It appears you put the name of the type in that definition.  The second parameter to the attribute is the _namespace_.  Try this instead:

`[assembly: XmlnsDefinition("http://schemas.microsoft.com/netfx/2009/xaml/activities", "CoreWf")]`

**Comment by ewinnington** [comment]
Oh! I'm further: Portable.Xaml.XamlException occurred
  HResult=0x80131500
  Message=ActivityXamlServices encountered a member (Sequence) that is not supported by DynamicActivity.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at CoreWf.XamlIntegration.DynamicActivityXamlReader.ProcessCurrentNode() \Repos\corewf\src\CoreWf\XamlIntegration\DynamicActivityXamlReader.cs:line 323
 
Thanks for your help! Now for some deeper stuff.

**Comment by cwensley** [comment]
No problem, let me know if you need more help!

**Comment by ewinnington** [comment]
I'm again a bit stuck... I have the sequence inside an activity, but I when I am looking for the CurrentMember: {http://schemas.microsoft.com/netfx/2009/xaml/activities}Activity.Sequence}

I get a null and throw this exception: ActivityXamlServices encountered a member (Sequence) that is not supported by DynamicActivity. 

[It occurs here](https://github.com/ewinnington/corewf/blob/master/src/CoreWf/XamlIntegration/DynamicActivityXamlReader.cs#L320) at 

```
XamlMember member = this.activityReplacementXamlType.GetMember(currentMember.Name);
                                if (member == null)
                                {
                                    throw CoreWf.Internals.FxTrace.Exception.AsError(CreateXamlException(SR.MemberNotSupportedByActivityXamlServices(currentMember.Name), this.innerReaderLineInfo));
                                }
```

At least, a simple `<Activity>` in XAML is returned as a DynamicActivity in C# and it can be invoked (but it does nothing yet).

There must still be something borked. If you have any ideas? Otherwise I'll keep picking at it until I find a solution.

**Comment by ewinnington** [comment]
Ok, I'm stuck. Help.

I can have the top level activity, even with InArguments and OutArguments that get parsed to a DynamicActivity, but as soon as I nest something in it such as a Sequence or an Assign, I get the exception: ActivityXamlServices encountered a member (Sequence / Assign / ...) that is not supported by DynamicActivity.

When I put a WriteLine nested inside the Activity, I don't get an exception, but I don't get back any implementation in the dynamicActivity. 

Any suggestions? I think I must be close, I just can't figure out what's wrong.

I ported a few more files for the InArguments and OutArguments. [The code is up in my fork](https://github.com/ewinnington/corewf). 

--

Update: I think I figured it out. It's the ContentPropertyAttribute that must be enabled all over the code. I'll be able to try that in a few hours.  

--

Update 2:
Yes, I get further: Now I have a new XAML exception while loading the WriteLine Activity:  
Portable.Xaml.XamlParseException occurred
  HResult=0x80131500
  Message=Read-only member 'Implementation' showed up in the source XML, and the xml contains element content that cannot be read. at line 1, position 154

--

Update 3: The definition of Implementation in Activity must be Public instead of Protected for Portable.XAML to access it. (`public virtual Func<Activity> Implementation`)

**Comment by ewinnington** [comment]
[Excellent news: First contents parsed successfully XAML -> DynamicActivity](https://github.com/ewinnington/corewf/commit/5e3c2a0ef87e019d7df225dd3b570c3ba91ad5df)
- Changed the visibility of Activity from protected to public allowed Portable.Xaml to reach the property and fill the Implementation body.

This commit allows XAML content to be successfully parsed to a DynamicActivity object. The `<Activity><WriteLine Text='HelloWorld'/></Activity>` is parsed successfully, but then fails when invoked due to the FuncFactory.Evaluate() "`XamlServices.Transform(this.Nodes.GetReader(), writer);`" being called. This requires the XamlReader which fails with a "`Portable.Xaml.XamlObjectWriterException: GetObject is not allowed at current state Initial`" exception. 


Update: When running CoreWf on the .net framework 4.6.2 with System.Xaml instead of Portable.Xaml, the `<Activity><WriteLine Text='HelloWorld'/></Activity>` successfuly writes HelloWorld out to the console. This indicates to me that the issue for Evaluate() is situated in Portable.Xaml.  @cwensley Any ideas? Is there something I could do to help track that down? 

--

The `<Activity><x:Members><...></x:Members><Assign><...></Assign></Activity>` fails with a "`System.Exception: should not happen`" during the ActivityXamlServices.Load().


Update: this activity also fails on the .net framework using system.Xaml, indicating to me that the CoreWf code is not yet complete enough to correctly load the `<Assign>` Expression. I'll look into that soon.

-- 

I now have to find out what is causing the Evaluate() function to fail. As it seems to claim it's an Invalid Xaml parsing state, I might need some help to understand what went wrong. We are so close to a HelloWorld from CoreWf **on dotnet core!**, because CoreWf **on dotnet framework succeeds!**

**Comment by dmetzgar** [comment]
Excellent progress so far. I'll be able to take a look at this sometime this week.

**Comment by ewinnington** [comment]
So the Assign activity seems to require visual basic compiling, correct me if I am wrong. So that's out until I get Roslyn working.

No progress today on the Evaluate() part.

**Comment by ewinnington** [comment]
I have issues with the parsing of the WriteLine activity. On Portable.Xaml + CoreWf + Core, I get 2 nodes inside Get and End without any values. It seems the start nodes are swallowed up. 

![image](https://user-images.githubusercontent.com/3533203/28546915-b06ccaba-70cc-11e7-8f74-3e60fe6a11f3.png)

On System.XAML + CoreWf + Framework, I get 5 nodes with the Start Object, Start Member and Value "HelloWorld" 

![image](https://user-images.githubusercontent.com/3533203/28546888-8cdf7b1a-70cc-11e7-8145-dd9fd0939c98.png)

Any suggestions as to where to look?

**Comment by ewinnington** [comment]
I'm currently blocked on this task. It seems I can't get any activity with a body to be parsed successfully. When I use system.xaml, it works, when I use Portable.Xaml, the parser seems to get in an invalid state.

I would need support either in tests to isolate what's wrong, or by someone taking a look to see if I've missed something evident to someone who understands the parsing of Xaml better than me. [Code is up in my fork.](https://github.com/ewinnington/corewf)

Demo project to check out is the [XAMLConsoleApp,](https://github.com/ewinnington/corewf/blob/master/test/XAMLConsoleApp/Program.cs) which parses various Activities.

The first Activity should succeed (L30-L34) even if it does nothing. 

Second activity (L45-50) succeeds when run on CoreWf + System.Xaml on the dot net framework, but fails on CoreWf + PortableXaml on dot net core, with the problem of the nodes of the WriteLine activity not containing the same information between System.Xaml and Portable.Xaml as described in the comment above.

Third Activity (L61-70) works with the properties, input dictionary is passed in and a 0 is return out since the outVariable is never set.

Fourth Activity (L88-102) seems to require a VisualBasic Variable (and some compilation) to use the Assign expression correctly. It currently fails. I hope that once we fix the others, I can make progress here.

Fifth Activity (L117-121) currently doesn't work, but should once we have the parsing of the Xaml corrected.

I expect to be able to spend some time over the week-end on this project. Hope someone can help move this issue forwards.

**Comment by ewinnington** [comment]
@dmetzgar It would really be helpful to either get tests or a little help on the Xaml parsing side, if you have any time to look into it.

I've added an Assign activity in the DynamicConsoleApp running in imperative code so the assign activity is created and compiled in code, that works. Seems like all the #3 is fully working and could be closed with a pull request if we bump the project to netstandard 2.0 or if we define it with 1.6/2.0 sections. 

On a positive side note, I'm able to confirm that CoreWf works on DotNetCore on Mac, editing with Visual Studio Mac 7.0.1 (v24) in NetStandard 2.0 once you fix the project to use `<NETStandardImplicitPackageVersion>2.0.0-preview1-25301-01</NETStandardImplicitPackageVersion> `. The examples BookmarkConsoleApp and DynamicConsoleApp all work with a dotnet run command. So I can also work with my iMac on this issue.

**Comment by dmetzgar** [comment]
Hey @ewinnington, sorry about that. Too many plates spinning at the same time. Let me get back to you later today with an update on the tests. Thanks for finding out how to get everything working on the Mac, that'll come in handy.

**Comment by ewinnington** [comment]
As a stopgap measure until we get Xaml parsing with the correct sub expression tree rewriter, what would you think of a converter that takes Xaml and outputs a .cs DynamicActivity in imperative code? Those two representation are nearly bijective, right? 

Send the generated code through a compiler and then you have a runnable activity. 

That probably doesn't work with the versioning of Xaml workflows for in place upgrades of long running workflows, but it's a step.

**Comment by Suriman** [comment]
@ewinnington What you are proposing, is not it exactly what the XAML parser does?.

**Comment by ewinnington** [comment]
No, the Xaml parser creates an in memory representation of the Xaml activities, with elements of Xaml that are kept as XamlNodeList for interpretation at runtime. 

I'm suggesting using a dumb XML reader (Xaml is valid xml) and generating DynamicActivity imperative source code that we then pass to a compiler. But it's just a pre-coffee morning idea...

**Comment by Suriman** [comment]
@ewinnington It is understood :-). 
Another option would be to use the DSL Tool from Microsoft and from a model (there is an example model: Task Flow Example) generate C # code that is compiled and executed by the workflow engine.

**Comment by ewinnington** [comment]
I am currently stuck on this task. Seeing no way forward without support from the WorfklowFoundation team or the System.Xaml team, [as I mentioned here](https://github.com/dotnet/corefx/issues/5766#issuecomment-320724209),  I filed the request for [System.Xaml to be added to reference source](https://github.com/Microsoft/referencesource/issues/39) for us to have the possibility to move forwards. 

@dmetzgar I understand you have a lot on your plate, but could you maybe help raise the issue at MS that the community wants to help, but we are limited without access to a xaml parser that correctly parses the workflow foundation files.

**Comment by cwensley** [comment]
@ewinnington If you could boil this down to what isn't working with Portable.Xaml and [submit an issue](https://github.com/cwensley/portable.xaml/issues) there, I could take a look at it.

**Comment by ewinnington** [comment]
@cwensley I've added to [Issue 91 in Portable.Xaml](https://github.com/cwensley/Portable.Xaml/issues/91) with an example of the difference in nodes between System.Xaml and Portable.Xaml. 

There is a zip with a Net Framework project attached.

**Comment by ewinnington** [comment]
The [pull request #98](https://github.com/cwensley/Portable.Xaml/pull/98) in Portable.XAML looks like it would unblock the XAML parsing for coreWF. As soon as I can, I'll continue on my branch. 

This fix allows:
```
<Activity 
x:Class=""WFTemplate"" 
xmlns=""http://schemas.microsoft.com/netfx/2009/xaml/activities"" 
xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"">  
<Sequence>
<WriteLine Text=""HelloWorld"" /> 
</Sequence>
</Activity>";
```
To be parsed and work successfully. 

Whereas is parsed successfully, but cannot yet be executed:
```
<Activity x:Class=""WFTemplate""  
xmlns=""http://schemas.microsoft.com/netfx/2009/xaml/activities""  
xmlns:s=""clr-namespace:System;assembly=mscorlib""  
xmlns:s1=""clr-namespace:System;assembly=System""  
xmlns:sa=""clr-namespace:CoreWf;assembly=CoreWf""  
xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml"">   
<x:Members>         
<x:Property Name=""myInput"" Type=""InArgument(x:String)"" />   
</x:Members>   
<WriteLine Text=""[myInput]"" /> 
</Activity>";
```

Doesn't work yet because in file [ActivityWithResultConverter.cs](https://github.com/ewinnington/corewf/blob/0bcfc0b228b7ba929eccdfeea492dcdbebb15f64/src/CoreWf/XamlIntegration/ActivityWithResultConverter.cs#L191-L199) the location helper needs to return a VisualBasicReference, which is something I haven't yet started on. You can see currently I have it set as //EBW NULLED 

```
class LocationHelper<TLocationValue> : LocationHelper
            {
                public override Activity CreateExpression(string expressionText)
                {
                    //return new VisualBasicReference<TLocationValue>()
                    //{
                    //    ExpressionText = expressionText
                    //};
                    //EBW NULLED
                    throw new NotImplementedException(System.Reflection.MethodBase.GetCurrentMethod().Name + System.Reflection.MethodBase.GetCurrentMethod().DeclaringType.FullName);
                }
            }
```

This needs to now be implemented to parse the [Variable] in the activity.

**Comment by ewinnington** [comment]
Update: So the [Portable.Xaml nuget package 0.22 has been published](https://www.nuget.org/packages/Portable.Xaml/0.22.0) with the fix that allows us to load XAML workflows into corewf.

I'll update my branch and clean it up with the new reference to 0.22 Portable.Xaml as soon as I have time.

@dmetzgar Is #7 the issue for the VisualBasicReference transformation of a XAML [Variable] to code in WF? Can you say more about how we could go about implementing it in CoreWF? Can we simply add and uncomment the VisualBasicReference files or do we need to pull in Roslyn to do the interpretation and generation of the code tree? Is there someone we can ask for help?

Sorry, many questions!

**Comment by dmetzgar** [comment]
@ewinnington, the VB compiler used for WF in the .NET Framework is an old set of native binaries that would be more difficult to port than using Roslyn instead. I'd love to get help with learning how to use Roslyn to parse VB/C# expressions into activities.
