### ISSUE TITLE
Use Roslyn for converting expression trees into activities

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#7]
The way the .NET Framework version of WF parses expressions is with a custom, unsupported compiler for VB and an MSBuild task for C#. It would be a significant improvement to use Roslyn for the .NET Standard/Core version of WF.

**Comment by ewinnington** [comment]
So this requires us to load a WF activity and implement the equivalent to [TextExpressionCompiler(settings).Compile();](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/csharp-expressions#CompiledXaml) with Roslyn instead of the previous compiler?

We should base ourselves on the API of the [TextExpressionCompiler.cs](https://github.com/Microsoft/referencesource/blob/4fe4349175f4c5091d972a7e56ea12012f1e7170/System.Activities/System/Activities/XamlIntegration/TextExpressionCompiler.cs) to limit the changes to WF, I guess?

**Comment by ewinnington** [comment]
I haven't abandoned this, but hoping for some quiet time over the holidays to progress. 

The public facing API of TextExpressionCompiler is very small and it seems that only Compile is called in the WF code. 
![image](https://user-images.githubusercontent.com/3533203/50280370-94ae7e80-044c-11e9-984d-52ea888610f6.png)

Having used Roslyn in a small project recently, I'll try to apply her here. 

I haven't found an active call to GenerateSource:
	TextExpressionCompiler.cs	GenerateSource 
is called by 
	XamlBuildProviderExtension.cs	<-	GenerateSource	<-	TryGenerateSource	<- GenerateCode
Which doesn't seem to be called in the Reference Source and XamlBuildProviderExtension is only used by WorkflowServiceHostFactory

**Comment by ewinnington** [comment]
#47 Covers this functionality.
