### ISSUE TITLE
Create a HTML workflow designer using ASP.NET Core

### ISSUE THREAD

**Issue by dmetzgar** [UiPath/CoreWF#9]

**Comment by novotx** [comment]
Sad to see there are no comments here, our company is heavily invested in the Windows Workflow Foundation.  We use it similar to how you describe (windows designer component included in our tools) but are looking to move all tools to the web so we are forced to either shop for a different workflow service, build our own web designer or look for ways to encourage/support the Microsoft team to transition the tool to the web along with the other items discussed.  I do feel that you are not getting a full interaction with the community as there isn't an "official" product page from Microsoft for specific components that come with the .NET Framework!  I feel WCF, WWF, WPF, etc. are all products but you end up filtering through many, many sites and pages published by Microsoft (and the community) to piece together the information you are looking for.  The fact that I am commenting on GitHub proves that point.  We are open to showing how we are using the WWF product (along with many of our partners) if it would prove beneficial.  WWF is a GREAT product that is mostly overlooked because of its complexity and "out of the box" thinking from traditional software development (build a canned module into a product to solve a business case rather than let WWF solve the problem).

**Comment by dmetzgar** [comment]
Here's an example of a product that could be used for designing workflows: https://www.jointjs.com/opensource

**Comment by Diaskhan** [comment]
Better use draw.io source code its fully free !
